### ISSUE TITLE
Balances transfer Script

### ISSUE THREAD

**Issue by agoora** [RafalSladek/masternode-tools#1]
Hello Rafal,

I would like to know if you can help me with a script to monitor in real time, the incoming transactions of Bitcoin-core wallet /master node that has multiple addresses (to which I have private keys) , and automatically and instantly transfer their balances, to another specific address, without my manual intervention.

Thanks.

**Comment by RafalSladek** [comment]
Hello, 
sorry but I never did this kind of operation
If you could hook up into the wallet notification than probably you can script a transfer to the other wallet. Have you checked redit?
